# i prefer Ctrl-o instead of the default Ctrl-b
unbind C-b
set -g prefix C-o
setw -g mode-keys vi
# use the spacebar to switch windows
unbind Space
bind Space next-window
# change split-window bindings
unbind %
unbind '"'
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
set -g mouse on
# sane scrolling:
#bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"
# disable esc-wait
set-option -sg  escape-time 0

set-option -g   history-limit 500000

set -g default-terminal "tmux-256color"

bind-key o send-prefix

# hardstatus line theme
set-option -g status-fg white
set-option -g status-bg black
set-option -g status-justify centre
set-option -g status-left-length 25
set-option -g status-left '#[fg=green,bg=black][#[fg=white,bg=black]#h#[fg=green,bg=black]]'
set-option -g status-right-length 40
set -g status-right '#[fg=green,bg=black][#[fg=white,bg=black]#($HOME/bin/loadavg)#[fg=green,bg=black]] [#[fg=white,bg=black]#(/bin/date "+%l:%M%p %m/%d/%y")#[fg=green,bg=black]]'

# Inactive windows in status bar
set-window-option -g window-status-format '#[fg=cyan,dim]#I#[fg=white]:#[default]#W#[fg=colour8,dim]#F'
 
# Current or active window in status bar
set-window-option -g window-status-current-format '#[bg=black,fg=red,bold](#[bg=black,fg=cyan,bold]#I#[fg=white]:#[fg=white]#W#[fg=dim]#F#[bg=black,fg=red])'

# tmux < 1.8: bind <prefix>-y to forward to Clipper
#bind-key y run-shell "tmux save-buffer - | nc localhost 8377"
#
# # tmux >= 1.8: bind "Enter" in copy mode to both copy and forward to Clipper
#bind-key -T copy-mode-vi Enter copy-pipe "nc localhost 8377"
